article/urls.py
from django.urls import path
from .views import new, detail, edit, destroy

app_name = 'article'

urlpatterns = [
    path("new/", new, name="new"),
    path("detail/<int:id>", detail, name="detail"),
    path("edit/<int:id>", edit, name="edit"),
    path("destroy/<int:id>", destroy, name="destroy"),
]

main/urls.py
from django.urls import path
from .views import index

app_name = 'main'

urlpatterns = [
    path("", index, name='index')
]

serengeti/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('main.urls')),
    path("users/", include('user.urls')),
    path("articles/", include('article.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import signin, signup, signout, new_profile, create_profile

app_name = 'user'

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("signin/", signin, name='signin'),
    path("signout/", signout, name="signout"),
    path('new_profile/', new_profile, name='new_profile'),
    path('create_profile/', create_profile, name='create_profile'),
]

article/models.py
from django.db import models


class Article(models.Model):
    author = models.ForeignKey('user.User', on_delete=models.CASCADE)
    title = models.TextField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True,)
    updated_at = models.DateTimeField(auto_now=True,)

main/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin


class UserManager(BaseUserManager):

    def _create_user(self, username, password, **kwargs):
        user = self.model(
            username=username,
            **kwargs
        )
        user.set_password(password)
        user.save()

    def create_user(self, username, password, **kwargs):
        self._create_user(username, password, **kwargs)

    def create_superuser(self, username, password, **kwargs):
        kwargs.setdefault('is_superuser', True)
        self._create_user(username, password, **kwargs)


class User(AbstractBaseUser, PermissionsMixin):

    USERNAME_FIELD = 'username'

    username = models.CharField(
        unique=True,
        max_length=20,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    objects = UserManager()

    @property
    def is_staff(self):
        return self.is_superuser


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    nickname = models.CharField(max_length=20, null=True)
    image = models.ImageField(upload_to='profile/', null=True)

    class Meta:
        db_table = 'profile'

    def __str__(self):
        return self.user.username, self.nickname

article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content',]

user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import TextInput
from django import forms
from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'jclass': 'form-control'}),
        label='유저이름'
    )


class UserSignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            'username'
        ]
        widgets = {
            'username': TextInput(attrs={
                'class': 'form-control',
                'style': 'background-color : skyblue',
                'placeholder': 'ID'
            })
        }
        labels = {
            'username': 'ID',
        }

article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ArticleForm
from .models import Article
from user.models import Profile


def new(request):
    form = ArticleForm()
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('article:detail', id=article.id)
    return render(request, 'new.html', {'form': form})


def detail(request, id):
    article = get_object_or_404(Article, pk=id)
    profile, created = Profile.objects.get_or_create(user=request.user)
    return render(request, 'detail.html', {'article': article, "profile": profile})


def edit(request, id):
    article = get_object_or_404(Article, pk=id)
    form = ArticleForm(instance=article)

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=Article)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', id=article.id)
    return render(request, 'edit.html', {'form': form, 'article': article})


def destroy(request, id):
    article = get_object_or_404(Article, pk=id)
    article.delete()
    return redirect('main:index')

main/views.py
from django.shortcuts import render
from article.models import Article
# Create your views here.


def index(request):
    articles = Article.objects.all()
    return render(request, "index.html", {"articles": articles})

user/views.py
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserSignupForm
from django.contrib.auth import login, logout
from .models import Profile


def signin(request):
    form = UserLoginForm()
    if request.method == 'POST':
        form = UserLoginForm(request, request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('main:index')
    return render(request, 'signin.html', {'form': form})


def signup(request):
    form = UserSignupForm()

    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:index')
    return render(request, 'signup.html', {"form": form})


def signout(request):
    logout(request)
    return redirect(request, 'main:index')


def new_profile(request):
    # 로그인 하지 않았다면 프로필 눌러도 홈으로 이동
    if request.user.is_anonymous:
        return redirect('main:index')
    # 로그인 했다면 해당 유저의 프로필 보기
    profile, created = Profile.objects.get_or_create(user=request.user)
    return render(request, 'newProfile.html', {"profile":profile})
    # 프로필이 원래 존재했으면 created=False

def create_profile(request):
    profile, created = Profile.objects.get_or_create(user=request.user)
    if request.method == "POST":
        profile.nickname = request.POST.get('nickname')
        profile.image = request.FILES.get('image')
        profile.save()
        return redirect('user:new_profile')
    return render(request, "newProfile.html", {'profile':profile})

article/templates/detail.html
상세페이지 id :
{{article.id}}
<br>
<h1>{{article.title}}</h1>
{% if profile.image %}
  <img src="{{profile.image.url}}" alt="프로필사진" width="100">
{% endif %}
<p>{{article.author.username}}</p>

<hr>
<p>{{article.content}}</p>

<a href={% url 'article:edit' article.id %}>수정하기</a>
<a href={% url 'article:destroy' article.id %}>삭제하기</a>
<a href={% url 'main:index' %}>홈으로</a>

article/templates/edit.html
수정

<form method="POST" action={% url 'article:new' %}>
  {% csrf_token %}
  {{form}}
    <button type='submit'>글 수정</button>
  </form>

article/templates/new.html
새글 작성

<form method="POST" action={% url 'article:new' %}>
  {% csrf_token %}
  {{form}}
    <button type='submit'>글 작성</button>
  </form>

main/templates/index.html
<h2>메인페이지</h2>

{% if user.is_authenticated %}
  <a href={% url 'user:signout' %}>로그아웃</a>
  <a href={% url 'article:new' %}>새글 작성</a>
  <a href={% url 'user:new_profile' %}>프로필 보기</a>
{% else %}
  <a href={% url 'user:signup' %}>회원가입</a>
  <a href={% url 'user:signin' %}>로그인</a>
{% endif %}

<hr>

{% for article in articles %}
  <div><a href={% url 'article:detail' id=article.id %}>
    {{article.title}}
    {{article.author.username}}
    {{article.content}}
    {% comment %} <a href={% url 'article:edit' id=article.id %}>글 수정</a>
    <a href={% url 'article:destroy' id=article.id %}>글 수정</a> {% endcomment %}
  </a><div>
    <br><hr>
{% endfor %}

user/templates/Signin.html
<body>
  <h2>로그인 페이지</h2>

  <form method="post" action="{% url 'user:signin' %}">
    {% csrf_token %}
    {{ form }}
      <button type="submit">로그인</button>
    </form>
  </body>

user/templates/Signup.html
<body>
  <h2>회원가입 페이지</h2>

  <form method="post" action="{% url 'user:signup' %}">
    {% csrf_token %}
    {{ form }}
      <button type="submit">회원가입</button>
    </form>
  </body>

user/templates/newProfile.html
<h1>프로필</h1>
<hr>

<h2>계정정보</h2>
<p>아이디:
  {{user.username}}</p>
<hr>

<h2>프로필 정보</h2>
<form method='POST' ,="," enctype='multipart/form-data' action="{% url 'user:create_profile' %}">{% csrf_token %}
  <label for="nickname">닉네임:</label>
  <input type='text' name='nickname' id='nickname' value="{{profile.nickname}}"/><br><br>
  <label for="image">프로필 사진:</label>
  {% if profile.image %}
    <img src="{{profile.image.url}}" alt="프로필사진" width="100">
    <br>
    <label>
      <input type='checkbox' name='remove_image'/>사진삭제</label>
    <br><br>
    {%endif%}
    <input type="file" name="image" id="image"/><br><br>
    <button type="submit">저장</button>
  </form>

  <a href="{% url 'main:index' %}">홈</a>